# Generated by Django 4.2.14 on 2026-07-04 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repository_url', models.URLField(max_length=500)),
                ('repository_owner', models.CharField(blank=True, default='', max_length=255)),
                ('repository_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_stage', models.CharField(blank=True, default='', max_length=100)),
                ('progress', models.IntegerField(default=0)),
                ('status_message', models.CharField(blank=True, default='', max_length=255)),
                ('repository_data', models.JSONField(blank=True, null=True)),
                ('architecture_data', models.JSONField(blank=True, null=True)),
                ('risk_data', models.JSONField(blank=True, null=True)),
                ('memory_data', models.JSONField(blank=True, null=True)),
                ('continuity_data', models.JSONField(blank=True, null=True)),
                ('final_analysis', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
